Cd(__DIR__);;

Option(OPTf_WARN_PAREN, OFF);
Option(OPTf_WARN_DUP_TYPES, OFF);

U8 *SNAILNET_NATIVE_DRIVER = "PCNet";

#include "NetFifo"

#include "Drivers/PCNet"

#include "NativeSocket"

#include "Ethernet"
#include "Arp"
#include "IPv4"
#include "Icmp"
#include "Tcp"
#include "Udp"
#include "Dns"
#include "Netcfg"
#include "NetHandlerTask"

Option(OPTf_WARN_PAREN, ON);
Option(OPTf_WARN_DUP_TYPES, ON);
